//constants for the app
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";
export const REMOVE_PRODUCT_FAILURE = "REMOVE_PRODUCT_FAILURE"; 
export const READ_PRODUCT_LIST = "READ_PRODUCT_LIST";
export const READ_UPDATE = "READ_UPDATE";
export const FAILURE_UPDATE = "FAILURE_UPDATE";
export const SUCCESS_UPDATE= "SUCCESS_UPDATE";
export const READ_PRODUCT = "READ_PRODUCT";
export const READ_CHART = "READ_CHART";